server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: open-ecommerce
  
  datasource:
    url: jdbc:h2:mem:ecommerce
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      
logging:
  level:
    com.openecommerce: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
# Business Configuration
business:
  settlement:
    cron: "0 0 2 * * ?"  # Daily at 2 AM
  currency:
    default: CNY
    precision: 2